-- MySQL Script generated by MySQL Workbench
-- 08/07/17 16:44:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hotel` ;
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Persona` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.L', 'C.E', 'R.C', 'Otros') NOT NULL,
  `Documento` BIGINT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Telefono` BIGINT UNSIGNED NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Tipo_Perfil` ENUM('Administrador', 'Recepcion', 'Cliente') NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  UNIQUE INDEX `Documento_UNIQUE` (`Documento` ASC),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`ServcioTelefonia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`ServcioTelefonia` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`ServcioTelefonia` (
  `idTelefonia` INT NOT NULL AUTO_INCREMENT,
  `Duracion` BIGINT NOT NULL,
  `Habitacion` VARCHAR(45) NOT NULL,
  `Tipo_Llamada` ENUM('Local', 'Nacional', 'Largadistancia') NOT NULL,
  `Valor` INT NULL,
  PRIMARY KEY (`idTelefonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Reservas` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Final` DATE NOT NULL,
  `Estado` ENUM('Activo','Inactivo') NOT NULL,
  `Tipo_Reserva` ENUM('Telefonica', 'Personal') NOT NULL,
  `Observacion` VARCHAR(200) NOT NULL,
  `Numero` INT NOT NULL,
  `Persona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `fk_Reservas_Persona1_idx` (`Persona` ASC),
  CONSTRAINT `fk_Reservas_Persona1`
    FOREIGN KEY (`Persona`)
    REFERENCES `Hotel`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Habitaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Habitaciones` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Habitaciones` (
  `idHabitaciones` INT NOT NULL AUTO_INCREMENT,
  `Foto` VARCHAR(60) NOT NULL,
  `Tipo_Habitacion` SET('Sencilla', 'Doble', 'Familiar') NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Piso` VARCHAR(45) NOT NULL,
  `Numero` INT(10) NOT NULL,
  `Vista` ENUM('Si', 'No') NOT NULL,
  `Valor` INT NULL,
  `Reservas` INT NOT NULL,
  `ServcioTelefonia` INT NOT NULL,
  PRIMARY KEY (`idHabitaciones`),
  INDEX `fk_Habitaciones_Reservas1_idx` (`Reservas` ASC),
  INDEX `fk_Habitaciones_ServcioTelefonia1_idx` (`ServcioTelefonia` ASC),
  CONSTRAINT `fk_Habitaciones_Reservas1`
    FOREIGN KEY (`Reservas`)
    REFERENCES `Hotel`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitaciones_ServcioTelefonia1`
    FOREIGN KEY (`ServcioTelefonia`)
    REFERENCES `Hotel`.`ServcioTelefonia` (`idTelefonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`Facturas` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`Facturas` (
  `idFacturas` INT NOT NULL AUTO_INCREMENT,
  `Persona` INT UNSIGNED NOT NULL,
  `Reservas` INT NOT NULL,
  `Habitaciones` INT NOT NULL,
  PRIMARY KEY (`idFacturas`),
  INDEX `fk_Facturas_Persona1_idx` (`Persona` ASC),
  INDEX `fk_Facturas_Reservas1_idx` (`Reservas` ASC),
  INDEX `fk_Facturas_Habitaciones1_idx` (`Habitaciones` ASC),
  CONSTRAINT `fk_Facturas_Persona1`
    FOREIGN KEY (`Persona`)
    REFERENCES `Hotel`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Reservas1`
    FOREIGN KEY (`Reservas`)
    REFERENCES `Hotel`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Habitaciones1`
    FOREIGN KEY (`Habitaciones`)
    REFERENCES `Hotel`.`Habitaciones` (`idHabitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`CuentaCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`CuentaCliente` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`CuentaCliente` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Cliente` VARCHAR(45) NOT NULL,
  `Persona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_CuentaCliente_Persona1_idx` (`Persona` ASC),
  CONSTRAINT `fk_CuentaCliente_Persona1`
    FOREIGN KEY (`Persona`)
    REFERENCES `Hotel`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`DatosEmpresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel`.`DatosEmpresa` ;

CREATE TABLE IF NOT EXISTS `Hotel`.`DatosEmpresa` (
  `idDatosEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nit` INT(20) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  `NumDIAN` INT(20) NOT NULL,
  `Persona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDatosEmpresa`),
  INDEX `fk_DatosEmpresa_Persona_idx` (`Persona` ASC),
  CONSTRAINT `fk_DatosEmpresa_Persona`
    FOREIGN KEY (`Persona`)
    REFERENCES `Hotel`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
